In [1]:
import numpy as np

In [3]:
array1 = np.arange(0,6)

In [4]:
array1

array([0, 1, 2, 3, 4, 5])

In [5]:
array1[2]

2

In [6]:
array1[1:4]

array([1, 2, 3])

set values in the range

In [7]:
array1[1:4] = 25

In [8]:
array1

array([ 0, 25, 25, 25,  4,  5])

Slicing of array

In [13]:
array2 = np.arange(0,10)

In [14]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
Slice = array2[0:6]

In [16]:
Slice

array([0, 1, 2, 3, 4, 5])

In [17]:
Slice[:] = 100

In [18]:
Slice

array([100, 100, 100, 100, 100, 100])

In [19]:
array2

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [20]:
array_copy = array2.copy()

In [21]:
array_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

Indexing in multidimensional array

In [22]:
array_md = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
array_md

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array_md[2]

array([7, 8, 9])

In [25]:
array_md[1,1]

5

In [27]:
array_md[:2,:2]

array([[1, 2],
       [4, 5]])

In [32]:
array_md[2,2]

9

In [33]:
array_md[1,2]

6