In [1]:
import numpy as np

In [2]:
array1 = np.arange(20).reshape((4,5))

In [3]:
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
array1.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

First row is changed to column as seen above

Dot Product of arrays

In [5]:
np.dot(array1.T,array1)

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

Create a 3d matrix

In [14]:
array2 = np.arange(20).reshape((2,5,2))

In [15]:
array2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

Swap axes

In [20]:
array3 = np.array([[1,2,3]])

In [21]:
array3

array([[1, 2, 3]])

In [22]:
array3.swapaxes(0,1)

array([[1],
       [2],
       [3]])