In [1]:
import numpy as np

In [2]:
array1 = np.arange(5)

In [3]:
array1

array([0, 1, 2, 3, 4])

In [4]:
np.save('newarray',array1)

In [6]:
array1 = np.arange(10)

In [7]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('newarray.npy')

array([0, 1, 2, 3, 4])

Save multiple arrays

In [10]:
arr1 = np.arange(3)

In [11]:
arr2 = np.arange(4)

In [12]:
np.save('new',arr1)

In [13]:
np.save('old',arr2)

In [15]:
np.load('new.npy')

array([0, 1, 2])

In [16]:
np.savez('ziparr.npz',x=arr1,y=arr2)

In [17]:
archieve_array = np.load('ziparr.npz')

In [18]:
archieve_array['x']

array([0, 1, 2])

to save a txt file

In [19]:
arr1= np.array([[1,2,3],[4,5,6]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('mytxtarr.txt',arr1,delimiter=',')

In [22]:
arr1 = np.loadtxt('mytxtarr.txt',delimiter=',')

In [23]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])