In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['a','s','d'])
ser2 = Series([3,4],index=['x','y'])


In [7]:
ser1

a    0
s    1
d    2
dtype: int64

In [8]:
ser2

x    3
y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

a    0
s    1
d    2
x    3
y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0    1
a  0.0  NaN
d  2.0  NaN
s  1.0  NaN
x  NaN  3.0
y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys= ['c1','c2'])

c1  a    0
    s    1
    d    2
c2  x    3
    y    4
dtype: int64

In [13]:
df1 =DataFrame(np.random.randn(4,3),columns = ['x','y','z'])

df2= DataFrame(np.random.randn(3,3),columns=['x','y','r'])

In [14]:
df1

x         y         z
0  0.584061 -0.099003 -2.309645
1  0.138576 -0.731980  0.582389
2  0.326050  0.327478  1.028761
3  0.332320  1.364070  1.477277

In [15]:
df2

x         y         r
0 -1.490807  0.829971 -0.336897
1  1.045185  0.162303  0.307251
2  0.310309 -1.352508  1.484862

In [16]:
pd.concat([df1,df2])

r         x         y         z
0       NaN  0.584061 -0.099003 -2.309645
1       NaN  0.138576 -0.731980  0.582389
2       NaN  0.326050  0.327478  1.028761
3       NaN  0.332320  1.364070  1.477277
0 -0.336897 -1.490807  0.829971       NaN
1  0.307251  1.045185  0.162303       NaN
2  1.484862  0.310309 -1.352508       NaN

In [17]:
pd.concat([df1,df2],ignore_index=True)

r         x         y         z
0       NaN  0.584061 -0.099003 -2.309645
1       NaN  0.138576 -0.731980  0.582389
2       NaN  0.326050  0.327478  1.028761
3       NaN  0.332320  1.364070  1.477277
4 -0.336897 -1.490807  0.829971       NaN
5  0.307251  1.045185  0.162303       NaN
6  1.484862  0.310309 -1.352508       NaN