In [1]:
import numpy as np

In [2]:
array1 = np.arange(11)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Universal functions are the operations that can be applied to every element in a array

In [5]:
np.sqrt(array1) #taking square root

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(array1) #taking exponential

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

Create random arrays

In [7]:
R1 = np.random.randn(10)
R1

array([-0.62566582, -0.449566  , -1.77638677,  1.06362951, -1.25547309,
        0.7269584 , -0.63483379, -2.15143829,  2.03591756, -0.21757917])

In [8]:
R2 = np.random.randn(10)
R2

array([ 0.87189904,  0.4698141 ,  0.52034358, -0.03495625,  0.24952801,
       -0.92329198, -1.23332767,  0.33948597,  1.30557451,  0.43297236])

Some operations like add etc

In [9]:
np.add(R1,R2)

array([ 0.24623322,  0.02024811, -1.25604319,  1.02867326, -1.00594508,
       -0.19633358, -1.86816146, -1.81195232,  3.34149206,  0.21539318])

Find maximum and min between arrays

In [10]:
np.maximum(R1,R2)

array([ 0.87189904,  0.4698141 ,  0.52034358,  1.06362951,  0.24952801,
        0.7269584 , -0.63483379,  0.33948597,  2.03591756,  0.43297236])

All other math functions can be seen here
https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html